server:
  port: 8080
  servlet:
    context-path: /momentum-invest
error:
  include-message: always
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/momentum
    username: postgres
    password: p@$$word
    initialization-mode: always
    initialize: true

  flyway:
    locations: classpath:db-setup
    baselineOnMigrate: "true"
    url: jdbc:postgresql://localhost:5432/momentum
    user: "postgres"
    password: "p@$$word"
    schemas: "public"
    enabled: true

